- .lgtm.yml
- profile_bluesky/startup/10-devices.py
- profile_bluesky/startup/21-signals.py
> support for Linkam temperature controllers

- profile_bluesky/startup/43-procedures.py
> mode_imaging

- profile_bluesky/startup/11-motors.py
fixes #111: guard slits are slow to move, needs better indication of completion
> end of move completion for gap change

- profile_bluesky/startup/usaxs_support/surveillance.py
fixes #228 archive custom user code
> #228 basic surveillance and archiving

- profile_bluesky/startup/spec/spec_config.py
> resolve LGTM alerts

- profile_bluesky/startup/29-axis_tuning.py
- profile_bluesky/startup/50-plans.py
> (re)set default tune ranges and other settings

- profile_bluesky/startup/50-plans.py
> enable option to move SX & SY in preUSAXStune()

- examples/README.md
- examples/custom_loop.md
- examples/simple_plan.md
- examples/use_linkam.md
- profile_bluesky/startup/09-imports.py
- profile_bluesky/startup/50-plans.py
- profile_bluesky/startup/usaxs_support/surveillance.py
> user custom plans need access to ipython namespace

- profile_bluesky/startup/10-devices.py
- profile_bluesky/startup/21-aps.py
> Ophyd signals for beam line diagnostics and post-mortem analyses

- profile_bluesky/startup/10-devices.py
- profile_bluesky/startup/43-procedures.py
- profile_bluesky/startup/50-plans.py
> gather terms used by both SAXS & WAXS

- profile_bluesky/startup/10-devices.py
> DCM_Feedback(): send email in thread

- profile_bluesky/startup/22-amplifiers.py
- profile_bluesky/startup/25-alta.py
> fix two errors spotted by LGTM

- profile_bluesky/startup/09-imports.py
- profile_bluesky/startup/11-motors.py
- profile_bluesky/startup/29-axis_tuning.py
- profile_bluesky/startup/29-guard_slit_tuning.py
- profile_bluesky/startup/51-tune_guard_slits.py
- profile_bluesky/startup/60-metadata.py
> plan: tune guard slits

- profile_bluesky/startup/10-devices.py
- profile_bluesky/startup/29-axis_tuning.py
- profile_bluesky/startup/32-usaxs_flyscan.py
- profile_bluesky/startup/43-procedures.py
- profile_bluesky/startup/50-plans.py
> get automatic retunes working

- profile_bluesky/startup/50-plans.py
> play the music when BS batch ends

- profile_bluesky/startup/32-usaxs_flyscan.py
fixes #271
**Do not merge until tested**
> do not fail the scan just because of updating program state

- profile_bluesky/startup/22-amplifiers.py
> fix autoscale failure

- profile_bluesky/startup/32-usaxs_flyscan.py
> fly scan reporting when timeouts from PyEpics

- profile_bluesky/startup/50-plans.py
> optional tune *ALWAYS BEFORE* mode change

- profile_bluesky/startup/01-databroker.py
> no baseline report before/after every plan runs

- .gitignore
- profile_bluesky/startup/09-imports.py
- profile_bluesky/startup/10-devices.py
- profile_bluesky/startup/29-axis_tuning.py
- profile_bluesky/startup/32-usaxs_flyscan.py
- profile_bluesky/startup/43-procedures.py
- profile_bluesky/startup/50-plans.py
- profile_bluesky/startup/usaxs_support/nexus.py
- profile_bluesky/startup/usaxs_support/saveFlyData.py
> refactor flyscan pv connections

- profile_bluesky/startup/09-imports.py
- profile_bluesky/startup/10-devices.py
- profile_bluesky/startup/32-usaxs_flyscan.py
> add device data as stream

- profile_bluesky/startup/43-procedures.py
> open shutter only if allowed in mode_Radiography()

- profile_bluesky/startup/43-procedures.py
> add reset_USAXS plan

- .gitignore
- profile_bluesky/startup/09-imports.py
- profile_bluesky/startup/10-devices.py
- profile_bluesky/startup/21-signals.py
- profile_bluesky/startup/22-amplifiers.py
- profile_bluesky/startup/32-uascan.py
- profile_bluesky/startup/50-plans.py
- profile_bluesky/startup/usaxs_support/ustep.py
> USAXS step scan : uascan

- profile_bluesky/startup/instrument/plans/mode_changes.py
- profile_bluesky/startup/instrument/plans/scans.py
> set value of user_data.collection_in_progress as appropriate

- profile_bluesky/startup/instrument/devices/alta.py
- profile_bluesky/startup/instrument/devices/area_detector_common.py
- profile_bluesky/startup/instrument/devices/blackfly.py
- profile_bluesky/startup/instrument/devices/for_apstools.py
- profile_bluesky/startup/instrument/devices/pilatus.py
- profile_bluesky/startup/instrument/devices/simdetector.py
> add 2 new PointGrey Blackfly cameras

- profile_bluesky/startup/instrument/callbacks/nxwriter.py
- profile_bluesky/startup/instrument/callbacks/nxwriter_usaxs.py
- profile_bluesky/startup/instrument/collection.py
- profile_bluesky/startup/instrument/framework/callbacks.py
- profile_bluesky/startup/instrument/plans/scans.py
- profile_bluesky/startup/instrument/plans/tune_guard_slits.py
- profile_bluesky/startup/instrument/utils/__init__.py
- profile_bluesky/startup/instrument/utils/setup_new_user.py
fixes #360, fixes #361, fixes #103
> Rearrange data location - master folder

- profile_bluesky/startup/instrument/plans/__init__.py
- profile_bluesky/startup/instrument/plans/no_run.py
- profile_bluesky/startup/instrument/plans/sample_transmission.py
> transmission should not create a run

- profile_bluesky/startup/usaxs_support/builder_362.py
- profile_bluesky/startup/usaxs_support/saveFlyData.xml
> add ESAF & Proposal data (NXuser) to fly scan files

- profile_bluesky/startup/instrument/devices/area_detector_common.py
- profile_bluesky/startup/instrument/devices/blackfly.py
- profile_bluesky/startup/instrument/plans/sample_imaging.py
- profile_bluesky/startup/instrument/plans/scans.py
- profile_bluesky/startup/usaxs_support/builder_382.py
- timestamp.db
> record JPEG of sample when scanning

- profile_bluesky/startup/instrument/plans/scans.py
- profile_bluesky/startup/instrument/utils/setup_new_user.py
fixes #388
Leave the working directory under the user's control.  The plans will control where the data is written.
> do not call chdir in newUser()

- profile_bluesky/startup/instrument/utils/setup_new_user.py
> specify directory for SPEC data file

- profile_bluesky/startup/instrument/devices/autocollect.py
- profile_bluesky/startup/instrument/plans/scans.py
> Raises Flag "in operations" properly before and after command

- profile_bluesky/startup/instrument/devices/autocollect.py
> print idle message when auto_collect is idle

- profile_bluesky/startup/instrument/devices/axis_tuning.py
- profile_bluesky/startup/instrument/devices/axis_tuning_patches.py
> make tune width a settable PV

- profile_bluesky/startup/instrument/devices/user_data.py
In changes to fix #428, the user will be able to change the sample name. This enables sample names based on conditions that change during a long of sequence of scans, such as a temperature series.
> User function can modify sample title. Use during scan sequence.

- profile_bluesky/startup/instrument/devices/ad_tiff_upstream.py
- profile_bluesky/startup/instrument/devices/area_detector_common.py
- profile_bluesky/startup/instrument/devices/blackfly.py
- profile_bluesky/startup/instrument/plans/sample_imaging.py
> blackfly2 should take TIFF images

- profile_bluesky/startup/instrument/devices/blackfly.py
- profile_bluesky/startup/instrument/plans/sample_imaging.py
> Control directory for blackfly2 images

- profile_bluesky/startup/instrument/plans/command_list.py
fixes #457 
Actually, just a work-around until we can resolve the random FailedStatus exceptions.
> Apply while..try..except to execution of command file.  Retry and keep going!

- profile_bluesky/startup/instrument/devices/diagnostics.py
- profile_bluesky/startup/instrument/plans/mode_changes.py
* FIX #303: watch more PSS signals, including mono shutter permit
* FIX #456: Don't fail modeRadiography when mono shutter cannot be opened
> PSS signals for doors and C station

- profile_bluesky/startup/instrument/plans/scans.py
- profile_bluesky/startup/instrument/utils/__init__.py
- profile_bluesky/startup/instrument/utils/user_sample_title.py
> Users want to update the sample title with dynamic information

- profile_bluesky/startup/instrument/plans/command_list.py
> Verify command files

- profile_bluesky/startup/instrument/devices/__init__.py
- profile_bluesky/startup/instrument/devices/laser.py
- profile_bluesky/startup/instrument/plans/mode_changes.py
> 511 add laser distance meter

- profile_bluesky/startup/instrument/devices/shutters.py
- profile_bluesky/startup/instrument/plans/command_list.py
> Enable autoopen on collection

- profile_bluesky/startup/instrument/plans/move_instrument.py
Adresses #528, hard interlocks are better, so limits changes are needless operation
> Removed limits changes

- profile_bluesky/startup/instrument/devices/suspenders.py
> Ensure feedback is ON during delay period when resuming from beam dump

- profile_bluesky/startup/instrument/plans/scans.py
- FIXES #487
Move getSampleTitile to better locations
> move call to getSampleTitle() closer to actual collection events

- .gitignore
- examples/dev_test_set.txt
- profile_bluesky/startup/instrument/plans/command_list.py
> add SET command for batch execution

- profile_bluesky/startup/instrument/utils/setup_new_user.py
> refactor newUser(), use CWD

- profile_bluesky/startup/instrument/devices/monochromator.py
> replace dcm with energy in monochromator
